server:
  port: 8085
  shutdown: GRACEFUL
logging:
  level:
    org.springframework.security: trace


spring:
  application:
    name: comrade-llm
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          comrade-news-client:
            client-id: "comrade-news"
            client-secret: "{noop}comrade-news"
            authorization-grant-type: client_credentials
            scope: openid,profile
            provider: comrade-news-client-prod
        provider:
          comrade-news-client-prod:
#            issuer-uri: http://localhost:9000
            token-uri: http://localhost:9000/oauth2/token



